# -*- coffee -*- -p
author: 'YC <yinso.chen@gmail.com>'
name: 'bundlet'
description: 'client-side Javascript packager.'
version: '0.1.0'
repository:
  type: 'git'
  url: 'git://github.com/yinso/bundlet.git'
main: './lib/'
bin: 
  bundlet: './bin/cli.js'
engines:
  node: '>= 0.8.4'
scripts:
  test: 'make test'
  prepublish: 'make'
dependencies:
  yargs: =1.3.3
  coffee-script: =1.8.0
  underscore: =1.7.0
  funclet: '>=0.1.0'
  loglet: '>=0.1.1'
  browser-resolve: =1.5.0
  detective: =4.0.0
  witwip: =1.0.3
devDependencies:
  testlet: '>= 0.2.0'
  'coffee-bean': '>=0.3.0'
  pegjs: =0.8.0

