// Generated by CoffeeScript 1.4.0
(function() {
  var resolve;

  resolve = require('browser-resolve');

  module.exports = {
    process: require.resolve('./process'),
    buffer: require.resolve('native-buffer-browserify'),
    Buffer: require.resolve('native-buffer-browserify'),
    console: require.resolve('console-browserify'),
    constants: require.resolve('constants-browserify'),
    crypto: require.resolve('crypto-browserify'),
    domain: require.resolve('domain-browser'),
    events: require.resolve('events/'),
    http: require.resolve('http-browserify'),
    https: require.resolve('https-browserify'),
    os: require.resolve('os-browserify/browser'),
    path: require.resolve('path-browserify'),
    punycode: require.resolve('punycode/'),
    querystring: require.resolve('querystring/'),
    stream: require.resolve('stream-browserify'),
    string_decoder: require.resolve('string_decoder/'),
    sys: require.resolve('util/util'),
    timers: require.resolve('timers-browserify'),
    tty: require.resolve('tty-browserify'),
    url: require.resolve('url/'),
    util: require.resolve('util/util'),
    vm: require.resolve('vm-browserify'),
    zlib: require.resolve('zlib-browserify')
  };

}).call(this);
