// Generated by CoffeeScript 1.4.0
(function() {
  var bundle, fs, funclet, loglet, path, run;

  bundle = require('./bundle');

  loglet = require('loglet');

  funclet = require('funclet');

  path = require('path');

  fs = require('fs');

  run = function(argv) {
    return bundle.bundle(argv._[0], argv, function(err, res) {
      var destPath, item, _i, _len, _results;
      if (err) {
        return loglet.croak(err);
      } else if (argv.output) {
        destPath = path.join(argv.output, path.basename(argv._[0], path.extname(argv._[0])) + '.js');
        return fs.writeFile(destPath, res.join(''), function(err) {
          if (err) {
            return loglet.croak(err);
          } else {
            return loglet.log('saved to', destPath);
          }
        });
      } else {
        try {
          _results = [];
          for (_i = 0, _len = res.length; _i < _len; _i++) {
            item = res[_i];
            _results.push(loglet.log(item));
          }
          return _results;
        } catch (e) {
          return loglet.croak(e);
        }
      }
    });
  };

  module.exports = {
    run: run
  };

}).call(this);
