// Generated by CoffeeScript 1.4.0
(function() {
  var draining, queue, _NOOP, _drainQueue;

  queue = [];

  draining = false;

  _drainQueue = function() {
    var current, item, _i, _len;
    if (draining) {
      return;
    }
    draining = true;
    current = queue;
    queue = [];
    for (_i = 0, _len = current.length; _i < _len; _i++) {
      item = current[_i];
      item();
    }
    return draining = false;
  };

  _NOOP = function() {};

  module.exports = {
    nextTick: function(proc) {
      queue.push(proc);
      if (!draining) {
        return setTimeout(_drainQueue, 0);
      }
    },
    title: 'browser',
    browser: true,
    env: {},
    argv: [],
    version: '',
    on: _NOOP,
    addListener: _NOOP,
    once: _NOOP,
    off: _NOOP,
    removeListener: _NOOP,
    removeAllListeners: _NOOP,
    emit: _NOOP,
    binding: function() {
      throw {
        error: 'not_supported',
        name: 'process.binding'
      };
    },
    cwd: function() {
      return '/';
    },
    chdir: function(dir) {
      throw {
        error: 'not_supported',
        name: 'process.chdir'
      };
    },
    umask: function() {
      return 0;
    }
  };

}).call(this);
